services:
  app:
    build: .
    command: ./mvnw spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3307/alura-case
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      API_SECURITY_TOKEN_SECRET: ${API_SECRET_KEY}
      API_SECURITY_TOKEN_VALIDITY: 30
      EMAIL_SENDER_USERNAME: ${EMAIL_SENDER_USERNAME}
      EMAIL_SENDER_PASSWORD: ${EMAIL_SENDER_PASSWORD}

    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - .:/usr/app
    depends_on:
      - database
  database:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: root
      MYSQL_DATABASE: alura-case
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3306
    expose:
      - 3307